### ISSUE TITLE
Shorten the readiness for oncokb-public

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2137]
We do not need to wait for 60s. Should change to
```
readinessProbe:
            httpGet:
              path: /v2/api-docs
              port: 9095
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
```
