### ISSUE TITLE
How to invalid/remove the cache when deploy oncokb-core to production

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2617]
In production deployment, if you turn on redis cache clearing on pod initialization, it's possible the old pod generates  new caches while the new pods are initializing. So even at the time the new pod deleted all old caches, they might still use the old cache newly generated by the old pods.

**Comment by zhx828** [comment]
We can use k8s rollingupdates feature to make sure the old instances are removed completely before all new pods initialized.
I use
```
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
```
